name: 'ali-cdn-sdk'
description: 'aliCloud cdn sdk'
author: 'iou90'
branding:
  icon: 'cloud-rain'
  color: 'green'
inputs:
  accessKeyId:
    required: true
    description: 'access key id'
  appSecret:
    required: true
    description: 'app secret'
  action:
    required: true
    description: 'action name'
  version:
    description: 'sdk version'
    default: '2018-05-10'
  parameters:
    description: 'action parameters, JSON array with "key" & "value", example: { "DomainName": "xxx.xxx.com", "FunctionNames": "back_to_origin_url_rewrite" }'
outputs:
  result:
    description: 'action result'
runs:
  using: 'node12'
  main: 'dist/index.js'
