name: 'aliCdn'
description: 'aliCloud cdn sdk'
author: 'iou90'
inputs:
  accessKeyId:
    required: true
    description: 'access key id'
  appSecret:
    required: true
    description: 'app secret'
  action:
    required: true
    description: 'action name'
  version:
    description: 'sdk version'
  parameters:
    description: 'action parameters, JSON array with "key" & "value", example: [{ "key": "DomainName", "value": "xxx.xxx.com"}]'
outputs:
  result:
    description: 'action result'
runs:
  using: 'node14'
  main: 'dist/index.js'
